# Generated by Django 3.2.7 on 2021-09-26 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
