# Generated by Django 3.2.7 on 2021-10-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
